#!/usr/bin/env php
<?php

declare(strict_types=1);

define('KIRPI_START', microtime(true));
define('BASE_PATH', __DIR__);

require BASE_PATH . '/vendor/autoload.php';

$app = require BASE_PATH . '/bootstrap/app.php';

// Console Kernel
$kernel = new \Core\Console\Kernel($app);

exit($kernel->handle($argv));