<?php

declare(strict_types=1);

namespace Core\Console\Commands;

use Core\Console\Command;

class MakeModuleCommand extends Command
{
    protected string $signature = 'make:module {name}';
    protected string $description = 'Create a new module skeleton (Controllers/Models/Views/routes)';

    public function handle(): int
    {
        $rawName = trim((string) $this->argument('name', ''));
        if ($rawName === '') {
            $this->error('Module name is required.');
            $this->line('Usage: php framework make:module Catalog');
            return 1;
        }

        $moduleName = $this->toStudly($rawName);
        if (!preg_match('/^[A-Z][A-Za-z0-9]*$/', $moduleName)) {
            $this->error('Invalid module name. Use alphanumeric StudlyCase value.');
            return 1;
        }

        $modulePath = BASE_PATH . '/modules/' . $moduleName;
        if (is_dir($modulePath)) {
            $this->error("Module already exists: modules/{$moduleName}");
            return 1;
        }

        $this->makeDirectory($modulePath . '/Controllers');
        $this->makeDirectory($modulePath . '/Models');
        $this->makeDirectory($modulePath . '/Views');
        $this->makeDirectory($modulePath . '/routes');

        $moduleSlug = strtolower(preg_replace('/(?<!^)[A-Z]/', '-$0', $moduleName) ?? $moduleName);
        $controllerClass = $moduleName . 'Controller';
        $modelClass = $moduleName;
        $table = strtolower(preg_replace('/(?<!^)[A-Z]/', '_$0', $moduleName) ?? $moduleName) . 's';

        file_put_contents(
            $modulePath . '/README.md',
            "# {$moduleName} Module\n\nGenerated by `php framework make:module {$moduleName}`.\n"
        );

        file_put_contents(
            $modulePath . '/Controllers/' . $controllerClass . '.php',
            $this->controllerTemplate($moduleName, $controllerClass)
        );

        file_put_contents(
            $modulePath . '/Models/' . $modelClass . '.php',
            $this->modelTemplate($moduleName, $modelClass, $table)
        );

        file_put_contents(
            $modulePath . '/routes/web.php',
            $this->webRoutesTemplate($moduleName, $moduleSlug, $controllerClass)
        );

        file_put_contents(
            $modulePath . '/routes/api.php',
            $this->apiRoutesTemplate($moduleName)
        );

        file_put_contents($modulePath . '/Views/.gitkeep', '');

        $this->success("Module created: modules/{$moduleName}");
        $this->line('Next: php framework make:crud ' . $moduleName . ' Item');

        return 0;
    }

    private function toStudly(string $value): string
    {
        $value = preg_replace('/[^A-Za-z0-9]+/', ' ', $value) ?? $value;
        $value = str_replace(' ', '', ucwords(strtolower(trim($value))));
        return $value;
    }

    private function makeDirectory(string $path): void
    {
        if (!is_dir($path)) {
            mkdir($path, 0755, true);
        }
    }

    private function controllerTemplate(string $moduleName, string $controllerClass): string
    {
        return <<<PHP
<?php

declare(strict_types=1);

namespace Modules\\{$moduleName}\\Controllers;

use Core\\Http\\Response;

class {$controllerClass}
{
    public function index(): Response
    {
        return Response::json([
            'ok' => true,
            'module' => '{$moduleName}',
            'message' => '{$moduleName} module is ready.',
        ]);
    }
}

PHP;
    }

    private function modelTemplate(string $moduleName, string $modelClass, string $table): string
    {
        return <<<PHP
<?php

declare(strict_types=1);

namespace Modules\\{$moduleName}\\Models;

use Core\\Model\\Model;

class {$modelClass} extends Model
{
    protected string \$table = '{$table}';
}

PHP;
    }

    private function webRoutesTemplate(string $moduleName, string $moduleSlug, string $controllerClass): string
    {
        return <<<PHP
<?php

declare(strict_types=1);

/** @var \\Core\\Routing\\Router \$router */

\$router->group([
    'prefix' => '/admin',
    'as' => 'admin.',
    'middleware' => ['auth', 'permission:admin-access'],
], function (\\Core\\Routing\\Router \$router): void {
    \$router->get('/{$moduleSlug}', [\\Modules\\{$moduleName}\\Controllers\\{$controllerClass}::class, 'index'])
        ->name('{$moduleSlug}.index');
});

PHP;
    }

    private function apiRoutesTemplate(string $moduleName): string
    {
        return <<<PHP
<?php

declare(strict_types=1);

/** @var \\Core\\Routing\\Router \$router */

\$router->group([
    'prefix' => '/api/v1',
    'middleware' => ['auth:api'],
], function (\\Core\\Routing\\Router \$router): void {
    // Module API routes for {$moduleName}
});

PHP;
    }
}

